// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9H3EW_f7oQZrYolPhAXVb6djwHhoxOMM',
    appId: '1:1062585058954:web:28a909afd957532e61cf73',
    messagingSenderId: '1062585058954',
    projectId: 'cloud-firestore4-5be91',
    authDomain: 'cloud-firestore4-5be91.firebaseapp.com',
    storageBucket: 'cloud-firestore4-5be91.firebasestorage.app',
    measurementId: 'G-X1KGD9DLQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4-AC_DdUtBqEFw5MEGsKwbtwfnIy-Dq8',
    appId: '1:1062585058954:android:15d93328c0e5f60d61cf73',
    messagingSenderId: '1062585058954',
    projectId: 'cloud-firestore4-5be91',
    storageBucket: 'cloud-firestore4-5be91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA502v-hfzkfY2OuhYIDYLzwfaNZIUpDg',
    appId: '1:1062585058954:ios:c62efe056d11e40a61cf73',
    messagingSenderId: '1062585058954',
    projectId: 'cloud-firestore4-5be91',
    storageBucket: 'cloud-firestore4-5be91.firebasestorage.app',
    iosBundleId: 'com.example.cloudFirestore4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9H3EW_f7oQZrYolPhAXVb6djwHhoxOMM',
    appId: '1:1062585058954:web:70867739e727033561cf73',
    messagingSenderId: '1062585058954',
    projectId: 'cloud-firestore4-5be91',
    authDomain: 'cloud-firestore4-5be91.firebaseapp.com',
    storageBucket: 'cloud-firestore4-5be91.firebasestorage.app',
    measurementId: 'G-S00HLN49B8',
  );

}