// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDarGUO1q-83EeS3r1PGx2KHFfp9aG9Bic',
    appId: '1:215228376653:web:2ae0b197e4724cbd0a5e04',
    messagingSenderId: '215228376653',
    projectId: 'cloud-firebase3',
    authDomain: 'cloud-firebase3.firebaseapp.com',
    storageBucket: 'cloud-firebase3.firebasestorage.app',
    measurementId: 'G-MMG8X6KRRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqnbFJKR-7lkdHTMCM2munYtEOZ6JLFYU',
    appId: '1:215228376653:android:c1f51c2e0ea40a3e0a5e04',
    messagingSenderId: '215228376653',
    projectId: 'cloud-firebase3',
    storageBucket: 'cloud-firebase3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo9GkdrX0vL5Tq43fOo1iL4JmxrevakGo',
    appId: '1:215228376653:ios:b4c0fdeadcd7f4570a5e04',
    messagingSenderId: '215228376653',
    projectId: 'cloud-firebase3',
    storageBucket: 'cloud-firebase3.firebasestorage.app',
    iosBundleId: 'com.example.cloudFirestore3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDarGUO1q-83EeS3r1PGx2KHFfp9aG9Bic',
    appId: '1:215228376653:web:ae571fb272a08de90a5e04',
    messagingSenderId: '215228376653',
    projectId: 'cloud-firebase3',
    authDomain: 'cloud-firebase3.firebaseapp.com',
    storageBucket: 'cloud-firebase3.firebasestorage.app',
    measurementId: 'G-8E12DYMHQH',
  );

}